# 02 - Xây dựng Data Mart

Notebook này chỉ đọc `data/clean/sales_final.csv` để tạo fact/dim và các aggregate mart theo nhiều chiều phân tích.

In [2]:
import site
import sys
from pathlib import Path

USER_SITE = site.getusersitepackages()
if Path(USER_SITE).exists() and USER_SITE not in sys.path:
    sys.path.insert(0, USER_SITE)

PROJECT_DIR = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
if str(PROJECT_DIR) not in sys.path:
    sys.path.insert(0, str(PROJECT_DIR))

import pandas as pd
import matplotlib.pyplot as plt

pd.set_option("display.max_columns", 120)
pd.set_option("display.float_format", "{:,.2f}".format)

from src.pipeline import load_final_sales, run_mart_stage
from src.config import MART_DIR

final_sales = load_final_sales()
print(final_sales.shape)
display(final_sales.head())

(55050, 38)

,Ngày chứng từ,Năm,Tháng,Quý,Năm-Tháng,Số chứng từ,ĐVT,Số lượng,Khối lượng KG,Đơn giá,Doanh số,Chiết khấu,Doanh thu thuần,Số lượng trả lại,Giá trị trả lại,Giá vốn đơn vị,Tổng giá vốn,Lợi nhuận,Lợi nhuận tính lại,Mã khách hàng,Tên khách hàng,Nhóm khách hàng,Mã sản phẩm,Tên sản phẩm,Nhóm sản phẩm,Loại sản phẩm,Kênh,Chi nhánh,Vùng doanh thu,Trả hàng,Giai đoạn,Nguồn dữ liệu,Có dữ liệu giá vốn,Cờ duplicate,Biên lợi nhuận,Tỷ lệ chiết khấu,Tỷ lệ hoàn trả,Giá trị TB/dòng
0,2023-01-01,2023,1,1,2023-01,202300000277,TUI,1.00,0.20,"127,000.00","127,000.00",0.00,"127,000.00",0.00,0.00,"57,715.00","57,715.00","69,285.00","69,285.00",O_CUS_0008,<NA>,Nhóm khách hàng nội địa,O_PRO_0002,<NA>,Hòa tan,<NA>,Online,<NA>,<NA>,Không,Trước tái cấu trúc,2023-2025,False,False,0.55,0.00,0.00,"127,000.00"
1,2023-01-01,2023,1,1,2023-01,202300000393,KG,14.50,14.50,"181,000.00","2,624,500.00",0.00,"2,624,500.00",0.00,0.00,"144,510.76","2,095,406.00","529,094.00","529,094.00",O_CUS_0095,<NA>,Nhóm khách hàng nội địa,O_PRO_0009,<NA>,Hòa tan,<NA>,Khác,<NA>,<NA>,Không,Trước tái cấu trúc,2023-2025,False,False,0.20,0.00,0.00,"2,624,500.00"
2,2023-01-01,2023,1,1,2023-01,202300000843,HOP,3.00,0.90,"59,500.00","178,500.00",0.00,"178,500.00",0.00,0.00,"32,565.00","97,695.00","80,805.00","80,805.00",O_CUS_0006,<NA>,Nhóm khách hàng nội địa,O_PRO_0006,<NA>,Hòa tan,<NA>,Online,<NA>,<NA>,Không,Trước tái cấu trúc,2023-2025,False,False,0.45,0.00,0.00,"178,500.00"
3,2023-01-01,2023,1,1,2023-01,202300002038,HOP,6.00,1.08,"47,600.00","285,600.00","13,335.00","272,265.00",0.00,0.00,"22,146.50","132,879.00","139,386.00","139,386.00",O_CUS_0006,<NA>,Nhóm khách hàng nội địa,O_PRO_0025,<NA>,Hòa tan,<NA>,Online,<NA>,<NA>,Không,Trước tái cấu trúc,2023-2025,False,False,0.51,0.05,0.00,"272,265.00"
4,2023-01-01,2023,1,1,2023-01,202300004095,TUI,8.00,12.80,"251,000.00","2,008,000.00",0.00,"2,008,000.00",0.00,0.00,"113,074.62","904,597.00","1,103,403.00","1,103,403.00",O_CUS_0149,<NA>,Nhóm khách hàng nội địa,O_PRO_0001,<NA>,Hòa tan,<NA>,Khác,<NA>,<NA>,Không,Trước tái cấu trúc,2023-2025,False,False,0.55,0.00,0.00,"2,008,000.00"

In [3]:
mart_result = run_mart_stage(final_sales)
marts = mart_result["marts"]
for name, df in marts.items():
    print(name, df.shape)

fact_sales (55050, 26)
dim_date (1194, 7)
dim_customer (380, 4)
dim_product (337, 5)
dim_channel (8, 2)
mart_overview_year (4, 17)
mart_time_month (41, 19)
mart_time_quarter (14, 18)
mart_channel (205, 19)
mart_product_group (90, 19)
mart_region (72, 19)
mart_customer_group (108, 19)
mart_channel_product (392, 20)
mart_quarter_channel (74, 19)
mart_pareto_customer_group (15, 21)

In [4]:
# Ph?n t?ch c?u tr?c fact/dim
display(marts["fact_sales"].head())
display(marts["dim_date"].head())
display(marts["dim_customer"].head())
display(marts["dim_product"].head())
display(marts["dim_channel"].head())

,sales_id,date_key,customer_key,product_key,channel_key,Số chứng từ,ĐVT,Số lượng,Khối lượng KG,Đơn giá,Doanh số,Chiết khấu,Doanh thu thuần,Số lượng trả lại,Giá trị trả lại,Giá vốn đơn vị,Tổng giá vốn,Lợi nhuận,Biên lợi nhuận,Tỷ lệ chiết khấu,Tỷ lệ hoàn trả,Trả hàng,Giai đoạn,Nguồn dữ liệu,Chi nhánh,Vùng doanh thu
0,1,20230101,163,2,6,202300000277,TUI,1.00,0.20,"127,000.00","127,000.00",0.00,"127,000.00",0.00,0.00,"57,715.00","57,715.00","69,285.00",0.55,0.00,0.00,Không,Trước tái cấu trúc,2023-2025,<NA>,<NA>
1,2,20230101,250,9,3,202300000393,KG,14.50,14.50,"181,000.00","2,624,500.00",0.00,"2,624,500.00",0.00,0.00,"144,510.76","2,095,406.00","529,094.00",0.20,0.00,0.00,Không,Trước tái cấu trúc,2023-2025,<NA>,<NA>
2,3,20230101,161,6,6,202300000843,HOP,3.00,0.90,"59,500.00","178,500.00",0.00,"178,500.00",0.00,0.00,"32,565.00","97,695.00","80,805.00",0.45,0.00,0.00,Không,Trước tái cấu trúc,2023-2025,<NA>,<NA>
3,4,20230101,161,25,6,202300002038,HOP,6.00,1.08,"47,600.00","285,600.00","13,335.00","272,265.00",0.00,0.00,"22,146.50","132,879.00","139,386.00",0.51,0.05,0.00,Không,Trước tái cấu trúc,2023-2025,<NA>,<NA>
4,5,20230101,304,1,3,202300004095,TUI,8.00,12.80,"251,000.00","2,008,000.00",0.00,"2,008,000.00",0.00,0.00,"113,074.62","904,597.00","1,103,403.00",0.55,0.00,0.00,Không,Trước tái cấu trúc,2023-2025,<NA>,<NA>

     date_key Ngày chứng từ   Năm  Quý  Tháng Tên tháng Năm-Tháng
0    20230101    2023-01-01  2023    1      1   Tháng 1   2023-01
18   20230102    2023-01-02  2023    1      1   Tháng 1   2023-01
48   20230103    2023-01-03  2023    1      1   Tháng 1   2023-01
75   20230104    2023-01-04  2023    1      1   Tháng 1   2023-01
111  20230105    2023-01-05  2023    1      1   Tháng 1   2023-01

   customer_key Mã khách hàng        Tên khách hàng Nhóm khách hàng
0             1    CUST_00001   Online Customer 001          Online
1             2    CUST_00002   Online Customer 002          Online
2             3    CUST_00003   Online Customer 003          Online
3             4    CUST_00004   Online Customer 004          Online
4             5    CUST_00005  Corporate Client 001       Corporate

   product_key Mã sản phẩm Tên sản phẩm Nhóm sản phẩm Loại sản phẩm
0            1  O_PRO_0001         <NA>       Hòa tan          <NA>
1            2  O_PRO_0002         <NA>       Hòa tan          <NA>
2            3  O_PRO_0003         <NA>       Hòa tan          <NA>
3            4  O_PRO_0004         <NA>       Hòa tan          <NA>
4            5  O_PRO_0005         <NA>       Hòa tan          <NA>

   channel_key    Kênh
0            1      GT
1            2  HORECA
2            3    Khác
3            4      MT
4            5     OEM

In [5]:
# C?c mart aggregate theo chi?u ??n v? k?t h?p chi?u
for table in ["mart_overview_year", "mart_time_month", "mart_time_quarter", "mart_channel", "mart_product_group", "mart_channel_product", "mart_pareto_customer_group"]:
    print("\n", table)
    display(marts[table].head())

print("Thu muc mart cho Tableau:", MART_DIR)

 mart_overview_year

,Năm,Giai đoạn,Doanh thu thuần,Lợi nhuận,Tổng giá vốn,Doanh số,Chiết khấu,Giá trị trả lại,Số lượng,Khối lượng KG,Số đơn hàng,Số khách hàng,Số sản phẩm,Biên lợi nhuận,Tỷ lệ chiết khấu,Tỷ lệ hoàn trả,Giá trị TB/đơn
0,2023,Trước tái cấu trúc,"38,154,695,993.00","8,763,674,472.08","29,391,021,520.92","38,163,671,870.00","8,975,877.00",0.00,"980,350.00","239,053.13",7136,163,67,0.23,0.00,0.00,"5,346,790.36"
1,2024,Trước tái cấu trúc,"39,930,169,808.00","9,359,486,280.00","30,570,683,528.00","39,940,886,090.00","10,716,282.00",0.00,"1,165,633.00","279,371.12",7235,191,72,0.23,0.00,0.00,"5,519,028.31"
2,2025,Trước tái cấu trúc,"40,816,618,384.81","9,758,773,664.00","31,057,844,720.81","40,825,804,211.81","9,185,827.00",0.00,"1,688,658.25","312,142.94",7670,225,95,0.24,0.00,0.00,"5,321,593.01"
3,2026,Sau tái cấu trúc,"18,727,782,269.37","7,244,223,491.37","11,483,558,778.00","19,134,470,789.33","268,242,266.00","67,667,058.00","468,019.00","390,446.78",13273,155,242,0.39,0.01,0.00,"1,410,968.30"

 mart_time_month

,Năm,Tháng,Năm-Tháng,Giai đoạn,Doanh thu thuần,Lợi nhuận,Tổng giá vốn,Doanh số,Chiết khấu,Giá trị trả lại,Số lượng,Khối lượng KG,Số đơn hàng,Số khách hàng,Số sản phẩm,Biên lợi nhuận,Tỷ lệ chiết khấu,Tỷ lệ hoàn trả,Giá trị TB/đơn
0,2023,1,2023-01,Trước tái cấu trúc,"3,560,249,002.00","775,218,999.00","2,785,030,003.00","3,560,640,880.00","391,878.00",0.00,"58,318.00","30,841.55",584,88,60,0.22,0.00,0.00,"6,096,316.78"
1,2023,2,2023-02,Trước tái cấu trúc,"2,672,415,444.00","555,770,626.00","2,116,644,818.00","2,673,796,460.00","1,381,016.00",0.00,"30,026.00","7,596.97",477,84,51,0.21,0.00,0.00,"5,602,548.10"
2,2023,3,2023-03,Trước tái cấu trúc,"3,159,237,356.00","787,712,617.00","2,371,524,739.00","3,159,574,990.00","337,634.00",0.00,"74,797.50","27,204.01",607,86,56,0.25,0.00,0.00,"5,204,674.39"
3,2023,4,2023-04,Trước tái cấu trúc,"1,673,823,152.00","438,235,667.00","1,235,587,485.00","1,674,473,670.00","650,518.00",0.00,"41,676.00","7,883.44",472,82,59,0.26,0.00,0.00,"3,546,235.49"
4,2023,5,2023-05,Trước tái cấu trúc,"2,114,582,932.00","600,443,581.00","1,514,139,351.00","2,115,679,970.00","1,097,038.00",0.00,"43,456.00","20,714.27",490,80,56,0.28,0.00,0.00,"4,315,475.37"

 mart_time_quarter

,Năm,Quý,Giai đoạn,Doanh thu thuần,Lợi nhuận,Tổng giá vốn,Doanh số,Chiết khấu,Giá trị trả lại,Số lượng,Khối lượng KG,Số đơn hàng,Số khách hàng,Số sản phẩm,Biên lợi nhuận,Tỷ lệ chiết khấu,Tỷ lệ hoàn trả,Giá trị TB/đơn
0,2023,1,Trước tái cấu trúc,"9,391,901,802.00","2,118,702,242.00","7,273,199,560.00","9,394,012,330.00","2,110,528.00",0.00,"163,141.50","65,642.53",1668,127,67,0.23,0.00,0.00,"5,630,636.57"
1,2023,2,Trước tái cấu trúc,"5,150,537,748.00","1,404,216,258.00","3,746,321,490.00","5,152,754,380.00","2,216,632.00",0.00,"112,079.00","39,593.67",1477,121,66,0.27,0.00,0.00,"3,487,161.64"
2,2023,3,Trước tái cấu trúc,"11,272,516,159.00","2,100,625,933.84","9,171,890,225.16","16,902,232,400.00","1,533,015.00",0.00,"579,271.00","89,325.25",1747,127,67,0.19,0.00,0.00,"6,452,499.23"
3,2023,4,Trước tái cấu trúc,"12,339,740,284.00","3,140,130,038.24","9,199,610,245.76","6,714,672,760.00","3,115,702.00",0.00,"125,858.50","44,491.69",2244,140,66,0.25,0.00,0.00,"5,498,993.00"
4,2024,1,Trước tái cấu trúc,"10,936,561,817.00","2,405,134,688.00","8,531,427,129.00","10,937,925,580.00","1,363,763.00",0.00,"663,346.00","92,254.46",1630,144,71,0.22,0.00,0.00,"6,709,547.13"

 mart_channel

,Năm,Tháng,Kênh,Giai đoạn,Doanh thu thuần,Lợi nhuận,Tổng giá vốn,Doanh số,Chiết khấu,Giá trị trả lại,Số lượng,Khối lượng KG,Số đơn hàng,Số khách hàng,Số sản phẩm,Biên lợi nhuận,Tỷ lệ chiết khấu,Tỷ lệ hoàn trả,Giá trị TB/đơn
0,2023,1,Khác,Trước tái cấu trúc,"904,939,386.00","248,492,300.00","656,447,086.00","905,055,620.00","116,234.00",0.00,"20,950.50","3,432.60",192,77,45,0.27,0.00,0.00,"4,713,225.97"
1,2023,1,MT,Trước tái cấu trúc,"4,428,800.00","2,232,972.00","2,195,828.00","4,428,800.00",0.00,0.00,96.00,10.40,2,1,3,0.50,0.00,0.00,"2,214,400.00"
2,2023,1,Online,Trước tái cấu trúc,"71,720,216.00","25,981,416.00","45,738,800.00","71,995,860.00","275,644.00",0.00,515.00,278.45,349,6,45,0.36,0.00,0.00,"205,502.05"
3,2023,1,Quán nội bộ,Trước tái cấu trúc,"222,903,000.00","72,844,274.00","150,058,726.00","222,903,000.00",0.00,0.00,"1,906.50",990.01,39,3,38,0.33,0.00,0.00,"5,715,461.54"
4,2023,1,Xuất khẩu,Trước tái cấu trúc,"2,356,257,600.00","425,668,037.00","1,930,589,563.00","2,356,257,600.00",0.00,0.00,"34,850.00","26,130.10",2,1,7,0.18,0.00,0.00,"1,178,128,800.00"

 mart_product_group

,Năm,Tháng,Nhóm sản phẩm,Giai đoạn,Doanh thu thuần,Lợi nhuận,Tổng giá vốn,Doanh số,Chiết khấu,Giá trị trả lại,Số lượng,Khối lượng KG,Số đơn hàng,Số khách hàng,Số sản phẩm,Biên lợi nhuận,Tỷ lệ chiết khấu,Tỷ lệ hoàn trả,Giá trị TB/đơn
0,2023,1,Hòa tan,Trước tái cấu trúc,"3,560,249,002.00","775,218,999.00","2,785,030,003.00","3,560,640,880.00","391,878.00",0.00,"58,318.00","30,841.55",584,88,60,0.22,0.00,0.00,"6,096,316.78"
1,2023,2,Hòa tan,Trước tái cấu trúc,"2,672,415,444.00","555,770,626.00","2,116,644,818.00","2,673,796,460.00","1,381,016.00",0.00,"30,026.00","7,596.97",477,84,51,0.21,0.00,0.00,"5,602,548.10"
2,2023,3,Hòa tan,Trước tái cấu trúc,"2,538,789,807.00","648,954,757.00","1,889,835,050.00","2,539,006,190.00","216,383.00",0.00,"71,486.50","24,450.41",373,53,48,0.26,0.00,0.00,"6,806,406.99"
3,2023,3,Rang xay,Trước tái cấu trúc,"620,447,549.00","138,757,860.00","481,689,689.00","620,568,800.00","121,251.00",0.00,"3,311.00","2,753.60",290,65,28,0.22,0.00,0.00,"2,139,474.31"
4,2023,4,Hòa tan,Trước tái cấu trúc,"1,003,470,716.00","288,186,084.00","715,284,632.00","1,003,554,770.00","84,054.00",0.00,"38,284.00","4,960.59",227,32,27,0.29,0.00,0.00,"4,420,575.84"

 mart_channel_product

,Năm,Tháng,Kênh,Nhóm sản phẩm,Giai đoạn,Doanh thu thuần,Lợi nhuận,Tổng giá vốn,Doanh số,Chiết khấu,Giá trị trả lại,Số lượng,Khối lượng KG,Số đơn hàng,Số khách hàng,Số sản phẩm,Biên lợi nhuận,Tỷ lệ chiết khấu,Tỷ lệ hoàn trả,Giá trị TB/đơn
0,2023,1,Khác,Hòa tan,Trước tái cấu trúc,"904,939,386.00","248,492,300.00","656,447,086.00","905,055,620.00","116,234.00",0.00,"20,950.50","3,432.60",192,77,45,0.27,0.00,0.00,"4,713,225.97"
1,2023,1,MT,Hòa tan,Trước tái cấu trúc,"4,428,800.00","2,232,972.00","2,195,828.00","4,428,800.00",0.00,0.00,96.00,10.40,2,1,3,0.50,0.00,0.00,"2,214,400.00"
2,2023,1,Online,Hòa tan,Trước tái cấu trúc,"71,720,216.00","25,981,416.00","45,738,800.00","71,995,860.00","275,644.00",0.00,515.00,278.45,349,6,45,0.36,0.00,0.00,"205,502.05"
3,2023,1,Quán nội bộ,Hòa tan,Trước tái cấu trúc,"222,903,000.00","72,844,274.00","150,058,726.00","222,903,000.00",0.00,0.00,"1,906.50",990.01,39,3,38,0.33,0.00,0.00,"5,715,461.54"
4,2023,1,Xuất khẩu,Hòa tan,Trước tái cấu trúc,"2,356,257,600.00","425,668,037.00","1,930,589,563.00","2,356,257,600.00",0.00,0.00,"34,850.00","26,130.10",2,1,7,0.18,0.00,0.00,"1,178,128,800.00"

 mart_pareto_customer_group

,Năm,Nhóm khách hàng,Giai đoạn,Doanh thu thuần,Lợi nhuận,Tổng giá vốn,Doanh số,Chiết khấu,Giá trị trả lại,Số lượng,Khối lượng KG,Số đơn hàng,Số khách hàng,Số sản phẩm,Biên lợi nhuận,Tỷ lệ chiết khấu,Tỷ lệ hoàn trả,Giá trị TB/đơn,Tỷ trọng doanh thu,Tỷ trọng lũy kế,Nhóm Pareto
1,2023,Nhóm khách hàng xuất khẩu,Trước tái cấu trúc,"22,509,128,863.92","3,890,541,431.97","18,618,587,431.95","25,332,093,260.00",0.00,0.00,"706,798.50","177,135.31",21,6,26,0.17,0.00,0.00,"1,071,863,279.23",0.59,0.59,Top 80%
0,2023,Nhóm khách hàng nội địa,Trước tái cấu trúc,"15,645,567,129.08","4,873,133,040.11","10,772,434,088.97","12,831,578,610.00","8,975,877.00",0.00,"273,551.50","61,917.82",7115,157,67,0.31,0.00,0.00,"2,198,955.32",0.41,1.00,Còn lại
3,2024,Nhóm khách hàng xuất khẩu,Trước tái cấu trúc,"24,790,907,200.00","4,440,459,294.00","20,350,447,906.00","24,790,907,200.00",0.00,0.00,"830,996.50","209,826.60",21,6,24,0.18,0.00,0.00,"1,180,519,390.48",0.62,0.62,Top 80%
2,2024,Nhóm khách hàng nội địa,Trước tái cấu trúc,"15,139,262,608.00","4,919,026,986.00","10,220,235,622.00","15,149,978,890.00","10,716,282.00",0.00,"334,636.50","69,544.52",7214,185,72,0.32,0.00,0.00,"2,098,594.76",0.38,1.00,Còn lại
4,2025,Nhóm khách hàng nước ngoài,Trước tái cấu trúc,"24,567,871,606.81","4,306,173,560.00","20,261,698,046.81","24,567,871,606.81",0.00,0.00,"926,333.00","232,190.54",28,6,33,0.18,0.00,0.00,"877,423,985.96",0.60,0.60,Top 80%

Thu muc mart cho Tableau: D:\DuAnTotNghiep\data\mart